### ISSUE TITLE
Errors on 3.0.0-RC1

### ISSUE THREAD

**Issue by hkirk** [playframework/scalatestplus-play#96] opened 2017-06-12 09:54 UTC
Tried RC1 on a simple repository with two tests

```scala
"Index controller" should {
    "return valid response" in {
      val controller = new IndexController()

      val result = controller.index().apply(FakeRequest())
      val bodyText = Helpers.contentAsString(result)
      bodyText should include ("<script src=\"/assets/client-opt.js\" type=\"text/javascript\"></script>")
    }
  }
```

```scala
"GET /" should {
    "return result" in {
      val Some(f) = route(app, FakeRequest(GET, "/"))

      ScalaFutures.whenReady(f) { result =>
        result.header.status mustBe OK
      }
    }
  }
```

And are seeing some strange errors

```
[info] controllers.IndexControllerTest *** ABORTED ***
[info]   java.lang.AbstractMethodError:
[info]   at play.api.mvc.Results$class.$init$(Results.scala:490)
[info]   at controllers.IndexController.<init>(IndexController.scala:5)
[info]   at controllers.IndexControllerTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(IndexControllerTest.scala:13)
[info]   at controllers.IndexControllerTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(IndexControllerTest.scala:12)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
```

Hope this helps.

**Comment by marcospereira** [comment] 2017-06-13 18:58
Hey @hkirk,

Could you provide a complete project that reproduces the problem? I'm asking because most of our sample projects are using scalatestplus-play and they have similar specs.

Thanks.

**Comment by marcospereira** [comment] 2018-08-17 06:18
Closing this since we cannot reproduce.

**Closed by marcospereira** 2018-08-17 06:18 UTC
