### ISSUE TITLE
OneAppPerSuite throws ClassCastException

### ISSUE THREAD

**Issue by gavares** [playframework/scalatestplus-play#55] opened 2016-05-28 20:54 UTC
scalatestplus-play version: 1.5.1 (also tested with 1.5.0)
play version: 2.5.2
scala: 2.11.8
sbt: 0.13.11

I have a test that mixes in `OneAppPerSuite`, starts an application and then runs some tests. All of the tests pass but after they have completed, the suite fails with an exception that is thrown from inside scalatestplus-play. The stacktrace:

```
[info]   java.lang.ClassCastException: scala.util.Success cannot be cast to java.lang.Boolean
[info]   at scala.runtime.BoxesRunTime.unboxToBoolean(BoxesRunTime.java:85)
[info]   at org.scalatestplus.play.OneAppPerSuite$$anonfun$run$1.apply(OneAppPerSuite.scala:144)
[info]   at org.scalatest.CompositeStatus.whenCompleted(Status.scala:891)
[info]   at org.scalatestplus.play.OneAppPerSuite$class.run(OneAppPerSuite.scala:144)
```

I've walked through the code in `OneAppPerSuite` and `CompositeStatus` and I can't see anything obviously wrong.

**Comment by gavares** [comment] 2016-06-02 06:36
Using scalatest version 3.0.0-M-15 seems to be the cause of the probem. Once I reverted to 2.2.6, the issue was resolved.

**Comment by njouanin** [comment] 2016-10-12 21:17
Hi, is there a fix or workaround currently available for this issue ?

**Comment by marcospereira** [comment] 2016-10-14 22:19
Hey @gavares and @njouanin,

Could you please submit a reproducible scenario here?

**Comment by njouanin** [comment] 2016-10-15 09:39
I'm using scalatestplus-play 1.5.1 with play 2.5.x and scalatest/scalactic 3.0.0
I'm running the documentation example: 
```
class SampleSpec extends PlaySpec with OneAppPerSuite {

  // Override app if you need a Application with other than
  // default parameters.
  implicit override lazy val app = new GuiceApplicationBuilder().configure(Map("ehcacheplugin" -> "disabled")).build()

  "The OneAppPerSuite trait" must {
    "provide an Application" in {
      app.configuration.getString("ehcacheplugin") mustBe Some("disabled")
    }
    "start the Application" in {
      Play.maybeApplication mustBe Some(app)
    }
  }
}
```

For me, the ClassCastException is raised in a test class which uses `should` matchers (`"something" should {...`) instead of must. When using `must` the following exception is thrown : 

```
[info] models.dao.SampleSpec *** ABORTED ***
[info]   java.lang.AbstractMethodError: models.dao.SampleSpec.convertToStringMustWrapper(Ljava/lang/String;Lorg/scalactic/source/Position;Lorg/scalactic/Prettifier;)Lorg/scalatest/MustMatchers$StringMustWrapper;
[info]   at models.dao.SampleSpec.<init>(SampleSpec.scala:29)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```
 I guess scalatestplus-play 1.5.x doesn't support scalatest/scalactic 3.0.0. When switching to scalatest/scalactic 2.2.6 the test runs fine. So I don't know if there's an issue here. Just waiting for a scalatestplus-play version compatible with scalatest 3.0.0

**Comment by mach-kernel** [comment] 2016-11-06 02:10
I have the same issue.

##### Class
```scala
class QuerySpec extends WordSpec with OneServerPerSuite with MustMatchers
```

##### Relevant SBT
```
libraryDependencies ++= Seq(
  "org.scalatest" % "scalatest_2.11" % "3.0.0" % Test,
  "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1" % Test
)
```

##### Console Output
```
[info] org.pack.age.test.database.QuerySpec *** ABORTED ***
[info]   java.lang.ClassCastException: scala.util.Success cannot be cast to java.lang.Boolean
[info]   at scala.runtime.BoxesRunTime.unboxToBoolean(BoxesRunTime.java:85)
[info]   at org.scalatestplus.play.OneServerPerSuite$$anonfun$run$1.apply(OneServerPerSuite.scala:182)
[info]   at org.scalatest.CompositeStatus.whenCompleted(Status.scala:886)
[info]   at org.scalatestplus.play.OneServerPerSuite$class.run(OneServerPerSuite.scala:182)
[info]   at org.birdfeed.chirp.test.database.QuerySpec.run(QuerySpec.scala:14)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:472)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by wsargent** [comment] 2016-11-08 17:52
Scalatest 3.0.0 is not compatible with Scalatestplus-play 1.5.x.  The version that it's built against is `"org.scalatest" %% "scalatest" % "2.2.6"`.  The master snapshot "3.0.0-SNAPSHOT" is built against scalatest 3.0.0.

**Comment by wsargent** [comment] 2016-11-08 19:38
Can you test out the milestone build:

https://groups.google.com/d/msg/play-framework/KLpcJGzqbbI/k9DENVgDBAAJ

"org.scalatestplus.play" %% "scalatestplus-play" % "2.0.0-M1" % Test

**Comment by mach-kernel** [comment] 2016-11-08 20:01
@wsargent Thanks for the prompt reply! I'm going to give this a shot and report back after I've ported over a few tests with some feedback.

**Comment by mach-kernel** [comment] 2016-11-11 03:43
@wsargent it works perfectly and I have not to the best of my ability have been able to break it (yet). I will try though. 🎉 

Thank you!

**Comment by marcospereira** [comment] 2017-03-01 22:18
Closing since now we have a version compatible with Scalatest 3.0.x.

**Closed by marcospereira** 2017-03-01 22:18 UTC
