### ISSUE TITLE
Can not resolve/import "org.scalatestplus.play.guice.GuiceOneServerPerSuite"

### ISSUE THREAD

**Issue by masoodg** [playframework/scalatestplus-play#68] opened 2016-10-13 13:01 UTC
Hi,

I want to use a fake application with custom configuration and need one server per suite (extends GuiceOneServerPerSuite)
It can not resolve/import org.scalatestplus.play.guice.GuiceOneServerPerSuite. I have following version in my build.sbt:

playVersion = "2.4.6"
ScalatestVersion = "3.0.0"
scalaTestPlus = 1.5.1"

Any idea what is the reason and what should I do?

Thanks

**Comment by marcospereira** [comment] 2016-10-14 22:22
Where are you seeing this error?

Also, keep in mind that Scalatest 3.0 support was not released yet. Version 1.5.1 depends on Scalatest 2.2.6 as you can see here:

https://github.com/playframework/scalatestplus-play/blob/1.5.1/build.sbt#L35

**Comment by wsargent** [comment] 2016-11-08 19:38
Can you test out the milestone build:

https://groups.google.com/d/msg/play-framework/KLpcJGzqbbI/k9DENVgDBAAJ

"org.scalatestplus.play" %% "scalatestplus-play" % "2.0.0-M1" % Test

**Comment by marcospereira** [comment] 2017-02-17 00:24
Please, test again using the following version:

```scala
"org.scalatestplus.play" %% "scalatestplus-play" % "2.0.0-M2" % Test
```

**Comment by wsargent** [comment] 2017-04-13 21:19
Closing -- can't reproduce.

**Closed by wsargent** 2017-04-13 21:19 UTC
