### ISSUE TITLE
"Versions, Versions, Versions" page out of date

### ISSUE THREAD

**Issue by PainterAndHacker** [playframework/scalatestplus-play#72] opened 2016-12-06 21:37 UTC
Just a heads up that the [Version, Versions, Versions](http://www.scalatest.org/plus/play/versions) page appears out of date. It was linked to from the Play 2.5 documentation, but the latest Play version it mentions as supported is 2.4.

**Comment by gmethvin** [comment] 2016-12-07 01:07
This is a duplicate of #54. I think @bvenners and Artima maintain the page. Perhaps if they're unable to update it we should just stop pointing to that page and move the information to the README. Though I'd prefer if they just took down the page completely and moved the information here.

**Closed by gmethvin** 2016-12-07 01:07 UTC

**Comment by marcospereira** [comment] 2016-12-07 03:28
> Perhaps if they're unable to update it we should just stop pointing to that page and move the information to the README.

Greg, see #44. I think your suggestion could be added as part of that issue.
